### ISSUE TITLE
Problem running on WebAssembly 

### ISSUE THREAD

**Issue by elgransan** [oqtane/Oqtane.Survey#2] opened 2021-03-27 15:29 UTC
When I run it in server mode it works ok, but when I switch to WebAssemby mode I get:

`An unhandled exception has occurred. See browser dev tools for details. Reload`

And in console I get:

`System.TypeLoadException: Could not load type of field 'Oqtane.Survey.Index+<LoadSurveyResultsData>d__13:args' (3) due to: Could not load file or assembly 'Radzen.Blazor, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.`

Any Idea?

I'm running in last Oqtane Version: 
![image](https://user-images.githubusercontent.com/9949584/112725634-0319fb00-8ef8-11eb-886f-dd8dd2cb4b0a.png)

I tried with direct installing from the app and cloning the repo too, I get the same error.

**Comment by ADefWebserver** [comment] 2021-03-27 15:43
Yeah I did not test it in WebAssemby mode. My bad 😬

I suspect I needed to copy the Radzen.dll to the Client project in the packaging.

Can you tell me  the exact steps you used to get Oqtane to run in WebAssemby mode? I tried and couldn't get it to work and that is why I didn't test in that mode.

Thank You

**Comment by elgransan** [comment] 2021-03-27 15:54
Not too much steps, only this on server settings:

![image](https://user-images.githubusercontent.com/9949584/112726277-4f1a6f00-8efb-11eb-98f8-00f262c44efd.png)

**Comment by ADefWebserver** [comment] 2021-03-27 15:55
Darn I tried that. Anyway I will try again this weekend and work on this. Thanks!

**Comment by elgransan** [comment] 2021-03-27 15:58
Maybe is a problem with my configuration, I tried to figure out what is happening but I couldn't solve it (I'm still learning this technology)

**Comment by sbwalker** [comment] 2021-03-27 21:08
@ADefWebserver the ModuleInfo.cs file in the Client project contains the implementation for IModule which contains a Dependencies property. This should contain a comma delimited list of all assemblies that need to be downloaded to the client when running on WebAssembly. Currently it only specifies the Survey Shared assembly (as it contains the Model). It should also contain Radzen and any other assemblies the Client project depends on.

**Comment by elgransan** [comment] 2021-03-27 21:27
Yes, I could make it work, this is what you need to change: (Adding a PR)
![image](https://user-images.githubusercontent.com/9949584/112735284-ad5e4680-8f29-11eb-8f51-0a3af51cf577.png)



Also, I'm having problems reinstalling the Module, when I delete the Module and then I install it again when I post a survey I get a database error, seems the uninstalling is not working ok.

**Comment by ADefWebserver** [comment] 2021-03-27 22:06
@sbwalker - Thanks!, I'll fix this when I get to my dev computer tomorrow.

**Comment by ADefWebserver** [comment] 2021-03-27 22:07
@elgransan - I will look at the PR tomorrow. Thanks!

**Comment by ADefWebserver** [comment] 2021-03-28 05:30
@sbwalker, @elgransan - I put in the fix, but when I run in WebAssembly mode I now get this error:

![image](https://user-images.githubusercontent.com/1857799/112743421-13f45c00-8f4c-11eb-895b-2df465ce2ce9.png)

**Comment by sbwalker** [comment] 2021-03-28 13:39
That is strange as @elgransan indicated that it was working for him after making this modification?

**Comment by elgransan** [comment] 2021-03-28 14:08
Yes it works for me, it is possible to see the real error? Maybe running it on kestrel?

**Comment by sbwalker** [comment] 2021-03-28 14:26
@ADefWebserver the 500 error message appears to be indicating that the server-side method being called is having an issue. You can put a breakpoint in the GetAssemblies method in InstallationController on the server and use standard debugging to step through the logic. My guess is that one of the items identified in the Dependencies property is not the name of a DLL.

**Comment by ADefWebserver** [comment] 2021-03-28 17:27
@sbwalker, @elgransan - Ok the good news is that the Module works in WebAssmebly (that is what is checked in).  Note, when I tested this, the database tables, for the Survey module, were already created.

The bad news is that, the new .nupkg package (you create this by building the Solution in "Release" mode), will not run the .sql scripts when you install it.

I have tried everything. When I open the package I can't actually see the .sql scripts. 

So I am stuck at this point.

**Comment by ADefWebserver** [comment] 2021-03-28 17:55
> Also, I'm having problems reinstalling the Module, when I delete the Module and then I install it again when I post a survey I get a database error, seems the uninstalling is not working ok.

@elgransan - I now see that I am running into the issue you ran into. It appears that adding those assemblies to **Dependencies** in **ModuleInfo.cs** prevents the .sql scripts from running when the module is installed. cc: @sbwalker

**Comment by ADefWebserver** [comment] 2021-03-28 19:05
I alter the code to remove the **Dependencies** in **ModuleInfo.cs**, so the only change is that I have increased the version to **1.1.0**, and that NuGet package will install, but the .sql scripts still-wont-run :(

I am so stuck.

**Comment by elgransan** [comment] 2021-03-28 19:16
Sorry today I can't help you, tomorrow I'll give a try. Yesterday I remove the database to reinstall the module, because I get a database error after uninstall and install again, It was the only way

**Comment by ADefWebserver** [comment] 2021-03-28 19:18
@elgransan - Understood. Thank you for your help. 

1. Version 1.0.0 (on Nuget now) works for me
2. The uninstall works for me
3. Installing 1.1.0 will work, but, the .sql database scripts will not run (even if I remove the **Dependencies** added in **ModuleInfo.cs**)

**Comment by elgransan** [comment] 2021-03-28 19:26
Maybe is a bug in Oqtane

**Comment by sbwalker** [comment] 2021-03-28 19:37
@ADefWebserver how did you uninstall the module? Did you do it through the Module Management user interface? And you are running Oqtane V2.0.1 or higher?

**Comment by ADefWebserver** [comment] 2021-03-28 19:54
@sbwalker -

1. The orginal issue, where it did not work with **WebAssembly** was because my development version of **Oqtane** was **not** V2.0.1 - upgrading that is what allowed the orginal **WebAssembly** issue to work :)
2. So, yes all my testing is using **Oqtane version 2.0.1**
3. My current "problem" is that when I increase the version, in the **Survey Module**, to **1.1.0** - - and create the **Oqtane.Survey.1.1.0.nupkg** (created using "Release" then Build) , it will install, but, the .sql scripts will not run.
4. I have downloaded the install version of **Oqtane V2.0.1** and manually upload **Oqtane.Survey.1.1.0.nupkg** and it will install but, the .sql scripts will **not** run
5. I then uninstall **Oqtane.Survey.1.1.0** (through the Module Management user interface), restart the Oqtane, then I download **Oqtane.Survey.1.0.0.nupkg** and manually install it, in the same install version of **Oqtane V2.0.1** and the .sql scripts **will** run

**Comment by ADefWebserver** [comment] 2021-03-28 20:14
Ok I found a fix (thank you both for your 'mental help')

1. I set version to 1.0.1 rather than 1.1.0 (not sure if this makes a difference)
2. In Moduleinfo.cs I set: ReleaseVersions = "1.0.0,1.0.1" (it was: ReleaseVersions = "1.0.0")

**Comment by ADefWebserver** [comment] 2021-03-28 20:26
> because I get a database error after uninstall

@elgransan - I can confirm the uninstall, will remove the Survey database tables, if after uninstalling, you go to **System Info** (in the **Admin Dashboard**) then **Restart Application**.

**Comment by elgransan** [comment] 2021-03-28 20:32
Excellent!

**Comment by ADefWebserver** [comment] 2021-03-28 22:59
@sbwalker - I updated the code and added a "Support Oqtane WebAssembly Mode" section to the Oqtane Radzen article at: https://blazorhelpwebsite.com/ViewBlogPost/46

**Closed as completed by ADefWebserver** 2021-03-28 22:59 UTC
